property.filename = logs
appenders = console, file

# \u0967. \u0915\u0902\u0938\u094B\u0932 \u0915\u0949\u0928\u094D\u092B\u093F\u0917\u0930\u0947\u0936\u0928 (Console)
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# \u0968. \u092B\u093E\u0908\u0932 \u0915\u0949\u0928\u094D\u092B\u093F\u0917\u0930\u0947\u0936\u0928 (File)
appender.file.type = File
appender.file.name = LOGFILE
appender.file.fileName = ${filename}/mylog.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# \u0969. \u0924\u0941\u092E\u091A\u094D\u092F\u093E com.practice.Log \u0915\u094D\u0932\u093E\u0938\u0938\u093E\u0920\u0940 \u0905\u091A\u0942\u0915 \u0932\u0949\u0917\u0930 \u092E\u0945\u092A\u093F\u0902\u0917
loggers = com.practice
logger.com.practice.name = com.practice.Log
logger.com.practice.level = ALL
logger.com.practice.appenderRefs = file
logger.com.practice.appenderRef.file.ref = LOGFILE

# \u096A. \u092E\u0941\u0916\u094D\u092F \u0930\u0942\u091F \u0932\u0949\u0917\u0930
rootLogger.level = ALL
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT
